### ISSUE TITLE
教练! 有时间加点功能喵?

### ISSUE THREAD

**Issue by mindcat** [coldnight/twqq#17]

**Comment by mindcat** [comment]
QAQ 不小心按下了回车喵...
资料: 
http://cqp.cc/t-11613-1-1
http://blog.csdn.net/default7/article/details/10261075

**Comment by coldnight** [comment]
这么详尽的资料, 你加了提个 pull request 呗, 最近实在抽不出时间.

**Comment by mindcat** [comment]
QAQ 那好吧喵 猫猫看看怎么实现喵

**Comment by mindcat** [comment]
看不懂源代码QAQ 只会用喵
